### ISSUE TITLE
JAVA_HOME not available in subsequent roles

### ISSUE THREAD

**Issue by getjack** [gantsign/ansible-role-java#237]
Hi everyone i'm having trouble with your gantsign.java role in version 9.1.0 on Ansible 2.7.15. My environment is [amazonlinux2](https://hub.docker.com/_/amazonlinux)

I have a playbook where this role runs as requirement for another role which requires a java installation. However, if i want to execute any java application, the JAVA_HOME property is not available in the "ansible shell" and execution will fail. Imagine a playbook like this:

```
- hosts: localhost
  connection: local
  roles:
    - role: gantsign.java
      vars:
        java_version: '11'
        java_is_default_installation: yes
        java_fact_group_name: java
        java_install_dir: /opt/java
    - role: myapplication
      vars:
        ec2_tag_instance_environment: dev
        ec2_tag_int_hostname: int-hostname
```
Any task using the JAVA_HOME property fails as it is not yet available in the environment. As you can see `java_is_default_installation` is set so the property will be exported to profile.d . I assume that even though it exists in profile.d the ansible shell is not updated with the property and fails in any subsequent run.

A common pattern would be to source the file like `source /etc/profile.d/profilefile` .

As workaround i export the property at runtime via the ansible_local fact by your role.

For reference: https://www.jeffgeerling.com/blog/2017/add-path-global-path-ansible

The same issue is also true for any subsequent play within the same playbook. E.g.
```
- hosts: localhost
  connection: local
  roles:
    - role: gantsign.java
      vars:
        java_version: '11'
        java_is_default_installation: yes
        java_fact_group_name: java
        java_install_dir: /opt/java

# Fails to pickup JAVA_HOME
- hosts: localhost
  connection: local
  roles:
      vars:
        ec2_tag_instance_environment: dev
        ec2_tag_int_hostname: int-hostname
```

Edit: I also tried to source the file in pre_tasks. Still failing.
```
  pre_tasks:
    - shell: source /etc/profile.d/java.sh
    - debug:
        msg: "JAVA_HOME is '{{ lookup('env','JAVA_HOME') | d('/opt/java/latest') }}'!"

# Picking up the var with lookup('env', 'JAVA_HOME') results in ''
```

My best guess is that either the Ansible Version used or the shebang in the java.sh script are part of the problem.

**Comment by getjack** [comment]
I was able to fix my issue by using the become property on the task starting the application

```
  become: yes
  become_user: "{{ myapplication_user }}"
  become_flags: '-i'
```

The -i flag is relevant to source the env.

**Comment by getjack** [comment]
I need to reopen this issue as the error still occurs with another binary, namely "keytool" which i use with the java_keytool ansible module.

It seems like ansible uses a no-login shell so /etc/profile.d is never sourced on runtime.

**Comment by getjack** [comment]
@freemanjp As contributor with the most commits, can you give me any feedback for this issue?

**Comment by getjack** [comment]
@freemanjp Can you give me any feedback?

**Comment by freemanjp** [comment]
@getjack sorry for the late reply (my day job has been keeping me too busy). I suggest setting the `JAVA_HOME` in `/etc/environment` using another role e.g.:
```yaml
    - role: weareinteractive.environment
      environment_config:
        JAVA_HOME: '{{ ansible_local.java.general.home }}'
```
Run this after the Java role (i.e. after `ansible_local.java.general.home` is set). 

`/etc/environment` is often sourced even when `profile.d` isn't.
